### ISSUE TITLE
IllegalStateException when used in AppCompatActivity

### ISSUE THREAD

**Issue by Piasy** [code-mc/loadtoast#22]
In my usage, I just create one LoadToast instance at activity's onCreate method, and reuse it in every show and stop.
The problem is that when I change my activity to extends AppCompatActivity, the program throw IllegalStateException, stack trace is:

``` java
09-27 19:21:15.282 25403-25403/? E/AndroidRuntime: java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
09-27 19:21:15.282 25403-25403/? E/AndroidRuntime:     at android.view.ViewGroup.addViewInner(ViewGroup.java:3562)
09-27 19:21:15.282 25403-25403/? E/AndroidRuntime:     at android.view.ViewGroup.addView(ViewGroup.java:3415)
09-27 19:21:15.282 25403-25403/? E/AndroidRuntime:     at android.view.ViewGroup.addView(ViewGroup.java:3391)
09-27 19:21:15.282 25403-25403/? E/AndroidRuntime:     at net.steamcrafted.loadtoast.LoadToast.checkZPosition(LoadToast.java:117)
09-27 19:21:15.282 25403-25403/? E/AndroidRuntime:     at net.steamcrafted.loadtoast.LoadToast.access$600(LoadToast.java:18)
09-27 19:21:15.282 25403-25403/? E/AndroidRuntime:     at net.steamcrafted.loadtoast.LoadToast$2.onGlobalLayout(LoadToast.java:46)
09-27 19:21:15.282 25403-25403/? E/AndroidRuntime:     at android.view.ViewTreeObserver.dispatchOnGlobalLayout(ViewTreeObserver.java:815)
09-27 19:21:15.282 25403-25403/? E/AndroidRuntime:     at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1821)
09-27 19:21:15.282 25403-25403/? E/AndroidRuntime:     at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1039)
09-27 19:21:15.282 25403-25403/? E/AndroidRuntime:     at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5648)
09-27 19:21:15.282 25403-25403/? E/AndroidRuntime:     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:761)
09-27 19:21:15.282 25403-25403/? E/AndroidRuntime:     at android.view.Choreographer.doCallbacks(Choreographer.java:574)
09-27 19:21:15.282 25403-25403/? E/AndroidRuntime:     at android.view.Choreographer.doFrame(Choreographer.java:544)
09-27 19:21:15.282 25403-25403/? E/AndroidRuntime:     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:747)
09-27 19:21:15.282 25403-25403/? E/AndroidRuntime:     at android.os.Handler.handleCallback(Handler.java:733)
09-27 19:21:15.282 25403-25403/? E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:95)
09-27 19:21:15.282 25403-25403/? E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:136)
09-27 19:21:15.282 25403-25403/? E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:5113)
09-27 19:21:15.282 25403-25403/? E/AndroidRuntime:     at java.lang.reflect.Method.invokeNative(Native Method)
09-27 19:21:15.282 25403-25403/? E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:515)
09-27 19:21:15.282 25403-25403/? E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
09-27 19:21:15.282 25403-25403/? E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609)
09-27 19:21:15.282 25403-25403/? E/AndroidRuntime:     at dalvik.system.NativeStart.main(Native Method)
```

And I just step into the single line, and found that `mView.getParent().getParent().getParent() == mParentView` was `true`. More detailed info is:
`mView`: `net.steamcrafted.loadtoast.LoadToastView{4243e6a8 V.ED.... ......ID 0,0-376,96}`  
`mView.getParent()`: `android.support.v7.internal.widget.ContentFrameLayout{424a0278 V.ED.... ......ID 0,0-720,1230 #1020002 android:id/content}`  
`mView.getParent().getParent()`: `android.support.v7.internal.widget.FitWindowsLinearLayout{4249f3f8 V.E..... ......ID 0,0-720,1230 #7f0c0062 app:id/action_bar_root}`  
`mView.getParent().getParent().getParent()`: `android.widget.FrameLayout{42454c48 V.E..... ......ID 0,50-720,1280}`  
`mParentView`: `android.widget.FrameLayout{42454c48 V.E..... ......ID 0,50-720,1280}`  
When my activity extends FragmentActivity, this problem never happened.

**Comment by code-mc** [comment]
Will be fixed, already have something prepared just need to finalize!

EDIT: Fixed in 1.0.9
