### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by XxGoliathusxX** [code-mc/loadtoast#30]
```
 LoadToast lt = new LoadToast(this);
        lt.setTextColor(Color.RED).setBackgroundColor(Color.GREEN).setProgressColor(Color.BLUE);
        lt.setText("Hallo");
        lt.show();

FATAL EXCEPTION: main
                                                                    Process: com.oli.fitnessapp, PID: 27811
                                                                    java.lang.NoClassDefFoundError: Failed resolution of: Lnet/steamcrafted/loadtoast/R$color;
                                                                        at net.steamcrafted.loadtoast.LoadToastView.<init>(LoadToastView.java:83)
                                                                        at net.steamcrafted.loadtoast.LoadToast.<init>(LoadToast.java:32)
                                                                        at com.oli.myfitnessapp.activities.LiveSelectActivity.onCreate(LiveSelectActivity.java:114)
                                                                        at android.app.Activity.performCreate(Activity.java:6052)
                                                                        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
                                                                        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2332)
                                                                        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2441)
                                                                        at android.app.ActivityThread.access$800(ActivityThread.java:162)
                                                                        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1349)
                                                                        at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                        at android.os.Looper.loop(Looper.java:135)
                                                                        at android.app.ActivityThread.main(ActivityThread.java:5431)
                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                        at java.lang.reflect.Method.invoke(Method.java:372)
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:914)
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:707)
                                                                     Caused by: java.lang.ClassNotFoundException: Didn't find class "net.steamcrafted.loadtoast.R$color" on path:
```

**Comment by code-mc** [comment]
Obligatory: What did you try already? Gradle sync? clean build? ... 

This is obviously something related to your own environment as an R.class bug is not something that is caused by bad programming, it just compiled incorrectly and didn't include the class in your dex.

**Comment by XxGoliathusxX** [comment]
Ok i fixed that. Took me a while.
I would like to use this library to notify the user if an operation was sucessful or not. How can I show the animation from sucess() or error() for a certain time?

**Comment by code-mc** [comment]
Read the README please, it is a really simple API.
